version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - postgres
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST=postgres
    volumes:
      - ./backend:/usr/src/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
    - ./frontend:/usr/src/app
    - /usr/src/app/node_modules
    command: npm run dev

volumes:
  mongo_data:
  pgdata:
